### PR TITLE
EZP-30384: Failed to create 'var/encore': Permission denied

### PR DESCRIPTION
**Pull request by dia-wro**
**JIRA**: https://jira.ez.no/browse/EZP-30384

### CODE REVIEW

**Comment by lserwatka** [comment]
Thank you, could you elaborate what is the real issue? Do you have symlink?

**Comment by dia-wro** [comment]
We use Deployer and it uses absolute paths like: `/var/www/<site_path>/releases/1/bin/console cache:warmup --no-interaction --env=prod --no-debug`
this ends with an error: Failed to create 'var/encore': Permission denied

**Comment by lserwatka** [comment]
@micszo we need to run a round of QA here

**Review by lserwatka — APPROVED** [review]

**Review by micszo — APPROVED** [review]
Didn't find issues, also after rebase with master.

**Comment by lserwatka** [comment]
@dia-wro you can update to 1.0.1 https://github.com/ezsystems/ezplatform-core/releases/tag/v1.0.1

**Pull request merged**
